version: '3'

services:
  apache:
    build: .
    container_name: ai
    image: calvincaulfield/ai
    ports:
      - ${AI_PORT}:${AI_PORT}
    restart: always
    environment:
      - AI_PORT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY



